### ISSUE TITLE
Where is the 3090 dog manager?

### ISSUE THREAD

**Issue by Zhangjinso** [YrralH/MyDoc#1]

**Comment by Zhangjinso** [comment]
。。。

**Comment by Zhangjinso** [comment]
，，

**Comment by YrralH** [comment]
~~WaibiWaibi~~
Great appreciation for your checking here. 3090 Dog Manager is a unfixed position. You can ask in the QQ group directly when seeking for help.

**Comment by Zhangjinso** [comment]
Thanks for your suggestion! I will close this issue! (waibibabo, end)
